### PR TITLE
Async await middlewares

### PR DESCRIPTION
**Pull request by jmeas**
For the writes, this doesn't make the code much cleaner. But it begins the process of making the read middleware much nicer.

I'll need to go back through to tidy things up further, but I see a good path forward here.

### CODE REVIEW

**Comment by jmeas** [comment]
This is failing because of the coverage task. istanbul doesn't parse async/await. Looks like Esprima 4.0 isn't out yet, which would add support. 🤔

**Comment by jmeas** [comment]
To resolve this, I made a quick test using Jest (I hadn't used Jest before), to see if they supported async/await. They do, so I dug into their source and found out that they just transpile your code with Babel under-the-hood. So that's what I'm doing here.

**Comment by vitaly-t** [comment]
What is the point of this code - `.catch(r => r);`? It does precisely nothing.

**Comment by jmeas** [comment]
`await` will **throw** the error if I allow the Promise to reject. I do not want that, because I'd get pretty annoyed needing to try/catch any async function. It also excludes the fn from optimization in v8.

By using `catch`, I'm not swallowing the errors. I'm converting a rejection into a resolution. Then, I'm checking if the resolved value is an error.

Compare:

```js
let result;
// A failed query will reject the Promise, so it must be try-catch'd when using `await`.
try {
  result = await query();
} catch (e) {
  result = e;
}

if (result instanceof Error) { ... }
```

```js
let result = await query().catch(r => r);

if (result instanceof Error) { ... }
```

**Comment by vitaly-t** [comment]
`if (result instanceof Error)` - is a dangerous assumption, it won't always pass ;)

**Comment by jmeas** [comment]
> is a dangerous assumption, it won't always pass ;)

Ah, is that so? In that case, I may need to refactor this! Can you provide an example where a failed query doesn't return an Error?

**Comment by vitaly-t** [comment]
For example, all methods that support result modification...

```js
db.one('query', params, row=>{
    throw 'bla-bla';
});
```

**Comment by vitaly-t** [comment]
Also, when using `task`/`tx` you can benefit from the automatic `try`/`catch` wrapping :wink:

**Pull request merged**
